# k8s/api-gateway-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway # Deve corresponder ao label dos Pods do api-gateway-deployment
  ports:
  - protocol: TCP
    port: 3000       # Porta pela qual o serviço é exposto DENTRO do cluster (e a que o NodePort encaminhará)
    targetPort: 3000 # Porta onde o contentor do api-gateway está a escutar
    # nodePort: 30000 # Opcional: Pode especificar uma NodePort (entre 30000-32767)
                      # Se não especificar, o Kubernetes escolherá uma automaticamente.
  type: NodePort     # Expõe o serviço nos IPs dos nós do cluster numa porta estática (NodePort)