# k8s/jwt-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  # Substitua o valor abaixo pelo resultado da codificação Base64 do SEU JWT_SECRET
  secret: b3NldXNlZ3JlZG9tdWl0b3NlY3JldG8=