# mariadb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  # Substitua o valor abaixo pelo resultado da sua password codificada em Base64
  MARIADB_ROOT_PASSWORD: MTIzNDU=